// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function CopyFile(arg1, arg2) {
  return window['go']['main']['App']['CopyFile'](arg1, arg2);
}

export function CreateDirectory(arg1) {
  return window['go']['main']['App']['CreateDirectory'](arg1);
}

export function CreateFile(arg1, arg2) {
  return window['go']['main']['App']['CreateFile'](arg1, arg2);
}

export function CreateWorkflow(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateWorkflow'](arg1, arg2, arg3);
}

export function DeleteDirectory(arg1) {
  return window['go']['main']['App']['DeleteDirectory'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DeleteWorkflow(arg1) {
  return window['go']['main']['App']['DeleteWorkflow'](arg1);
}

export function DisableSkill(arg1) {
  return window['go']['main']['App']['DisableSkill'](arg1);
}

export function DownloadFile(arg1) {
  return window['go']['main']['App']['DownloadFile'](arg1);
}

export function EnableSkill(arg1) {
  return window['go']['main']['App']['EnableSkill'](arg1);
}

export function ExecuteSkillByName(arg1) {
  return window['go']['main']['App']['ExecuteSkillByName'](arg1);
}

export function ExecuteWorkflow(arg1, arg2) {
  return window['go']['main']['App']['ExecuteWorkflow'](arg1, arg2);
}

export function GetCacheStats() {
  return window['go']['main']['App']['GetCacheStats']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetPoolStats() {
  return window['go']['main']['App']['GetPoolStats']();
}

export function GetSkill(arg1) {
  return window['go']['main']['App']['GetSkill'](arg1);
}

export function GetSkillDefinition(arg1) {
  return window['go']['main']['App']['GetSkillDefinition'](arg1);
}

export function GetSkillSystemInfo() {
  return window['go']['main']['App']['GetSkillSystemInfo']();
}

export function GetSkillSystemStats() {
  return window['go']['main']['App']['GetSkillSystemStats']();
}

export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}

export function GetWorkflow(arg1) {
  return window['go']['main']['App']['GetWorkflow'](arg1);
}

export function GetWorkflowExecutionResult(arg1) {
  return window['go']['main']['App']['GetWorkflowExecutionResult'](arg1);
}

export function GetWorkflowExecutionResults(arg1) {
  return window['go']['main']['App']['GetWorkflowExecutionResults'](arg1);
}

export function GetWorkflowVersion(arg1, arg2) {
  return window['go']['main']['App']['GetWorkflowVersion'](arg1, arg2);
}

export function GetWorkflowVersions(arg1) {
  return window['go']['main']['App']['GetWorkflowVersions'](arg1);
}

export function GetWorkflows() {
  return window['go']['main']['App']['GetWorkflows']();
}

export function ImportSkillFromContent(arg1, arg2) {
  return window['go']['main']['App']['ImportSkillFromContent'](arg1, arg2);
}

export function ImportSkillFromFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportSkillFromFile'](arg1, arg2, arg3);
}

export function ImportSkillFromURL(arg1, arg2) {
  return window['go']['main']['App']['ImportSkillFromURL'](arg1, arg2);
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function ListRegisteredSkills() {
  return window['go']['main']['App']['ListRegisteredSkills']();
}

export function ListSkillDefinitions() {
  return window['go']['main']['App']['ListSkillDefinitions']();
}

export function MoveFile(arg1, arg2) {
  return window['go']['main']['App']['MoveFile'](arg1, arg2);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function ReloadSkillDefinitions() {
  return window['go']['main']['App']['ReloadSkillDefinitions']();
}

export function RestoreWorkflowVersion(arg1, arg2) {
  return window['go']['main']['App']['RestoreWorkflowVersion'](arg1, arg2);
}

export function ToggleSkill(arg1) {
  return window['go']['main']['App']['ToggleSkill'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateWorkflow(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateWorkflow'](arg1, arg2, arg3, arg4);
}

export function UploadFile(arg1, arg2) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2);
}

export function ValidateSkillFile(arg1) {
  return window['go']['main']['App']['ValidateSkillFile'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
