// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {agent} from '../models';

export function ClearCache():Promise<void>;

export function CopyFile(arg1:string,arg2:string):Promise<void>;

export function CreateDirectory(arg1:string):Promise<void>;

export function CreateFile(arg1:string,arg2:string):Promise<void>;

export function CreateWorkflow(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function DeleteDirectory(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DeleteWorkflow(arg1:string):Promise<void>;

export function DisableSkill(arg1:string):Promise<void>;

export function DownloadFile(arg1:string):Promise<Array<number>>;

export function EnableSkill(arg1:string):Promise<void>;

export function ExecuteSkillByName(arg1:main.ExecuteSkillInput):Promise<main.ExecuteSkillOutput>;

export function ExecuteWorkflow(arg1:string,arg2:string):Promise<string>;

export function GetCacheStats():Promise<main.CacheStats>;

export function GetConfig():Promise<agent.HostConfig>;

export function GetFileInfo(arg1:string):Promise<agent.FileInfo>;

export function GetPoolStats():Promise<main.PoolStats>;

export function GetSkill(arg1:string):Promise<agent.SkillMetadata>;

export function GetSkillDefinition(arg1:string):Promise<main.SkillDefinitionInfo>;

export function GetSkillSystemInfo():Promise<main.SkillSystemInfo>;

export function GetSkillSystemStats():Promise<main.SkillSystemStats>;

export function GetSkills():Promise<Record<string, agent.SkillMetadata>>;

export function GetWorkflow(arg1:string):Promise<agent.WorkflowInfo>;

export function GetWorkflowExecutionResult(arg1:string):Promise<agent.WorkflowExecutionResult>;

export function GetWorkflowExecutionResults(arg1:string):Promise<Array<agent.WorkflowExecutionResult>>;

export function GetWorkflowVersion(arg1:string,arg2:number):Promise<agent.WorkflowVersion>;

export function GetWorkflowVersions(arg1:string):Promise<Array<agent.WorkflowVersion>>;

export function GetWorkflows():Promise<Array<agent.WorkflowInfo>>;

export function ImportSkillFromContent(arg1:string,arg2:main.ImportSkillOptions):Promise<main.ImportSkillResult>;

export function ImportSkillFromFile(arg1:Array<number>,arg2:string,arg3:main.ImportSkillOptions):Promise<main.ImportSkillResult>;

export function ImportSkillFromURL(arg1:string,arg2:main.ImportSkillOptions):Promise<main.ImportSkillResult>;

export function ListFiles(arg1:string):Promise<Array<agent.FileInfo>>;

export function ListRegisteredSkills():Promise<Array<main.SkillListItem>>;

export function ListSkillDefinitions():Promise<Array<main.SkillDefinitionInfo>>;

export function MoveFile(arg1:string,arg2:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function ReloadConfig():Promise<void>;

export function ReloadSkillDefinitions():Promise<void>;

export function RestoreWorkflowVersion(arg1:string,arg2:number):Promise<void>;

export function ToggleSkill(arg1:string):Promise<boolean>;

export function UpdateConfig(arg1:agent.HostConfig):Promise<void>;

export function UpdateWorkflow(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UploadFile(arg1:string,arg2:Array<number>):Promise<void>;

export function ValidateSkillFile(arg1:string):Promise<Record<string, any>>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
