// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agent} from '../models';

export function ChatWithAgent(arg1:string,arg2:string):Promise<string>;

export function ClearCache():Promise<void>;

export function CopyFile(arg1:string,arg2:string):Promise<void>;

export function CreateDirectory(arg1:string):Promise<void>;

export function CreateFile(arg1:string,arg2:string):Promise<void>;

export function CreateWorkflow(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DeleteDirectory(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DeleteWorkflow(arg1:string):Promise<void>;

export function DisableSkill(arg1:string):Promise<void>;

export function DownloadFile(arg1:string):Promise<void>;

export function EnableSkill(arg1:string):Promise<void>;

export function ExecuteWorkflow(arg1:string,arg2:string):Promise<string>;

export function GetAgentInfo(arg1:string):Promise<Record<string, any>>;

export function GetConfig():Promise<agent.HostConfig>;

export function GetSkillInfo(arg1:string):Promise<agent.SkillMetadata>;

export function GetWorkflow(arg1:string):Promise<agent.WorkflowInfo>;

export function GetWorkflowExecutionResult(arg1:string):Promise<agent.WorkflowExecutionResult>;

export function GetWorkflowVersions(arg1:string):Promise<Array<agent.WorkflowVersion>>;

export function GetWorkflows():Promise<Array<agent.WorkflowInfo>>;

export function ImportWorkflowFromJSON(arg1:string):Promise<string>;

export function ListAgents():Promise<Array<string>>;

export function ListFiles(arg1:string,arg2:number):Promise<Array<agent.FileInfo>>;

export function ListSkills():Promise<Array<agent.SkillMetadata>>;

export function ReadFile(arg1:string):Promise<string>;

export function RegisterSkillFromMap(arg1:Record<string, any>):Promise<string>;

export function UpdateConfig(arg1:Record<string, any>):Promise<void>;

export function UpdateWorkflow(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
