// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatWithAgent(arg1, arg2) {
  return window['go']['main']['App']['ChatWithAgent'](arg1, arg2);
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function CopyFile(arg1, arg2) {
  return window['go']['main']['App']['CopyFile'](arg1, arg2);
}

export function CreateDirectory(arg1) {
  return window['go']['main']['App']['CreateDirectory'](arg1);
}

export function CreateFile(arg1, arg2) {
  return window['go']['main']['App']['CreateFile'](arg1, arg2);
}

export function CreateWorkflow(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateWorkflow'](arg1, arg2, arg3);
}

export function DeleteDirectory(arg1) {
  return window['go']['main']['App']['DeleteDirectory'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DeleteWorkflow(arg1) {
  return window['go']['main']['App']['DeleteWorkflow'](arg1);
}

export function DisableSkill(arg1) {
  return window['go']['main']['App']['DisableSkill'](arg1);
}

export function DownloadFile(arg1) {
  return window['go']['main']['App']['DownloadFile'](arg1);
}

export function EnableSkill(arg1) {
  return window['go']['main']['App']['EnableSkill'](arg1);
}

export function ExecuteWorkflow(arg1, arg2) {
  return window['go']['main']['App']['ExecuteWorkflow'](arg1, arg2);
}

export function GetAgentInfo(arg1) {
  return window['go']['main']['App']['GetAgentInfo'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetSkillInfo(arg1) {
  return window['go']['main']['App']['GetSkillInfo'](arg1);
}

export function GetWorkflow(arg1) {
  return window['go']['main']['App']['GetWorkflow'](arg1);
}

export function GetWorkflowExecutionResult(arg1) {
  return window['go']['main']['App']['GetWorkflowExecutionResult'](arg1);
}

export function GetWorkflowVersions(arg1) {
  return window['go']['main']['App']['GetWorkflowVersions'](arg1);
}

export function GetWorkflows() {
  return window['go']['main']['App']['GetWorkflows']();
}

export function ImportWorkflowFromJSON(arg1) {
  return window['go']['main']['App']['ImportWorkflowFromJSON'](arg1);
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListFiles(arg1, arg2) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2);
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RegisterSkillFromMap(arg1) {
  return window['go']['main']['App']['RegisterSkillFromMap'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateWorkflow(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateWorkflow'](arg1, arg2, arg3, arg4);
}
